### ISSUE TITLE
User can Initialize a Board

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/reversi#1]
# Motivation
We want to be able to initialize a board, and set a turn randomly. 

# Task Implementation
- [x] Create a function that creates an empty board.
- [x] Create a function that returns and prints the board.
- [x] Create a function to initialize tiles on the center of the board based on who is going first. 
- [x] Create a class to unify the game state, complete with the turn, the players, and the board's current configuration.
